version: '3.8'

services:
  backend:
    build:
      context: ../script/backend  
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - destination_db
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ../script/frontend 
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  destination_db:
    image: mysql:8.0
    container_name: destination_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: destination_db
    ports:
      - "3307:3306"
    volumes:
      - dest_db_data:/var/lib/mysql

volumes:
  dest_db_data:
